apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  selector:
    app: python-app
  type: { ? { .Values.service.type } }
  ports:
  - port: { ? { .Values.service.port } }
    targetPort: { ? { .Values.containerPort } }
