name: Build, Lint, and Push to ECR

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug runner environment
      run: |
        echo "Runner OS: $RUNNER_OS"
        echo "GitHub API Status: $(curl -s -o /dev/null -w '%{http_code}' https://api.github.com)"
        curl -s -o /dev/null -w '%{http_code}' https://api.github.com/internal/immutable-actions/actions/setup-python/download/sha256:2c4a1cc87f8d42f4ec181fc96fab063830330212bef88dc00f11285a0126fcbb
        git --version
        ping -c 4 api.github.com

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r python-app/requirements.txt

    - name: Install flake8
      run: pip install flake8

    - name: Verify flake8 installation
      run: flake8 --version

    - name: Lint Python code
      run: flake8 python-app/

    - name: Run tests
      run: pytest python-app/tests/

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          python-app/ --push

    - name: Scan Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
        format: table
        exit-code: '1'
        severity: CRITICAL,HIGH
