name: CI/CD for Flask App

on:
  push:
    branches:
    - main
    paths:
    - 'python-app/**'
  pull_request:
    branches:
    - main
    paths:
    - 'python-app/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      ECR_REPOSITORY: dev-flask-crud-repo

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python-app/requirements.txt

    - name: Lint Python code
      run: flake8 python-app/

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Build, tag, and push Docker image
      run: |
        IMAGE_URI=${{ secrets.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
        docker build -t $IMAGE_URI:${{ github.sha }} -t $IMAGE_URI:latest python-app/
        docker push $IMAGE_URI:${{ github.sha }}
        docker push $IMAGE_URI:latest
